version: "3"
services:
  webserver:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 81:80
    tty: true
  database:
    image: postgres:latest
    ports:
      - 5431:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  api:
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    build:
      context: ./api
      dockerfile: ./Dockerfile
      args:
        RAILS_ENV: ${RAILS_ENV}
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    depends_on:
      - database
      - webserver
    tty: true
    stdin_open: true
